### ISSUE TITLE
cleaner working HO viterbi

### ISSUE THREAD

**Issue by nrnrnr** [ndaniels/MRFy#14] opened 2013-05-18 20:10 UTC
Take the commit tagged `first-consistent-ho-viterbi` from the `nr-jfp` branch and see if you can  get the compiler to specialize the `internal [ edge ... ]` computation by abstracting over the `preceders` and `emission` functions and telling the compiler to inline.  Right now there are four calls to `internal`; it would be fantastic if each could be replaced by a call to a single function that is pragma'd to be inlined, without losing peformance.

**Comment by BurntSushi** [comment] 2013-05-18 20:33
Intentional dupe of https://github.com/ndaniels/MRFy-ICFP/issues/18

**Comment by BurntSushi** [comment] 2013-05-19 19:28
Done in https://github.com/ndaniels/MRFy/commit/abb74289030172d9e689d9a13cc3400d5b87eed4.

**Closed as completed by BurntSushi** 2013-05-19 19:28 UTC
